//! Regression coverage for issue #2885 — Angelic Field Marshal's Lieutenant
//! ability must produce TWO independent continuous effects whose scopes do not
//! collapse into one another.
//!
//! Oracle text:
//!   "Flying
//!    Lieutenant — As long as you control your commander, this creature gets
//!    +2/+2 and creatures you control have vigilance."
//!
//! The fixed parser (PR #3039, `try_split_and_foreign_subject_grant`) splits the
//! single Lieutenant clause into two `StaticDefinition`s, BOTH gated on
//! `ControlsCommander { Own }`:
//!   def0: affected = SelfRef                          → +2/+2
//!   def1: affected = Typed { Creature, controller=You } → grants Vigilance
//!
//! CR 611.3a: each conjunct is an independent continuous effect generated by the
//! static ability. CR 613.1f: the keyword grant is a Layer 6 ability-adding
//! effect applied on its own scope (creatures you control), while the +2/+2 is a
//! Layer 7c effect on the source alone — the two scopes must NOT be conflated.
//!
//! THE BUG this discriminates: if the two effects collapse into one scope, either
//! the +2/+2 leaks onto every creature you control, or Vigilance is restricted to
//! the source only. Scenario A's assertions (b) — second P0 creature has Vigilance
//! but is NOT +2/+2 — is the discriminating check: it fails if the scopes merge.
//!
//! This drives the REAL parse → layer pipeline: each creature is built from Oracle
//! text via the scenario harness (same `synthesize_all` as production), a
//! battlefield commander turns the Lieutenant gate ON
//! (CR 903.3d / CR 109.5: a commander on the battlefield owned AND controlled by
//! you), and the EFFECTIVE (post-`evaluate_layers`) power/toughness and keywords
//! are read back. It is a runtime test, not an AST-shape test.

use engine::game::keywords::has_keyword;
use engine::game::layers::evaluate_layers;
use engine::game::scenario::{GameRunner, GameScenario};
use engine::types::identifiers::ObjectId;
use engine::types::keywords::Keyword;
use engine::types::phase::Phase;
use engine::types::player::PlayerId;

const P0: PlayerId = PlayerId(0);
const P1: PlayerId = PlayerId(1);

/// Angelic Field Marshal — base 3/3; Flying; Lieutenant grants +2/+2 to itself
/// and Vigilance to creatures you control while you control your commander.
const ANGELIC_FIELD_MARSHAL: &str = "Flying\n\
Lieutenant — As long as you control your commander, this creature gets +2/+2 and creatures you control have vigilance.";

/// Recompute layers and read an object's effective (post-layer) power/toughness.
/// Mirrors `effective_pt` in `level_up_keywords.rs`.
fn effective_pt(runner: &mut GameRunner, id: ObjectId) -> (i32, i32) {
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
    let obj = &runner.state().objects[&id];
    (
        obj.power.expect("creature has power"),
        obj.toughness.expect("creature has toughness"),
    )
}

/// True iff `id` currently has `keyword` after a fresh layer evaluation.
fn has_kw(runner: &mut GameRunner, id: ObjectId, keyword: &Keyword) -> bool {
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
    has_keyword(&runner.state().objects[&id], keyword)
}

#[test]
fn angelic_field_marshal_lieutenant_splits_into_two_scopes() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);

    // Angelic Field Marshal (P0), built from Oracle text through the real
    // parse + synthesis pipeline (same synthesize_all path as production).
    let marshal = scenario
        .add_creature_from_oracle(P0, "Angelic Field Marshal", 3, 3, ANGELIC_FIELD_MARSHAL)
        .id();

    // A second vanilla creature for P0 — the discrimination subject for the
    // "Vigilance grant, but NOT +2/+2" scope check.
    let bears = scenario.add_creature(P0, "Grizzly Bears", 2, 2).id();

    // An opponent vanilla creature (P1) — must be untouched by both effects.
    let opp = scenario.add_creature(P1, "Runeclaw Bear", 2, 2).id();

    // Turn the Lieutenant gate ON: a battlefield permanent owned AND controlled
    // by P0 flagged `is_commander`. Mirrors `make_commander` in `layers.rs:4391`
    // (battlefield, owner == controller == P0) — NOT `with_commander`, which
    // moves the object to the command zone and makes `controls_own_commander`
    // (commander.rs:76) return false.
    //
    // CR 903.3d / CR 109.5: "you control your commander" is satisfied by a
    // commander on the battlefield both owned and controlled by you. `add_creature`
    // already sets owner == controller == P0; we only flip the commander flag.
    let commander = scenario.add_creature(P0, "Test Commander", 3, 3).id();

    let mut runner = scenario.build();

    // ----- Scenario A: Lieutenant gate ON -----
    runner
        .state_mut()
        .objects
        .get_mut(&commander)
        .expect("commander object exists")
        .is_commander = true;

    // (a) Angelic Field Marshal: +2/+2 AND Vigilance (granted to itself as a
    // creature you control). CR 611.3a: both conjuncts active under the gate.
    assert_eq!(
        effective_pt(&mut runner, marshal),
        (5, 5),
        "gate ON: Angelic Field Marshal is base 3/3 + 2/2"
    );
    assert!(
        has_kw(&mut runner, marshal, &Keyword::Vigilance),
        "CR 702.20a: Angelic Field Marshal gains Vigilance (a creature you control)"
    );

    // (b) Second P0 creature: Vigilance YES, +2/+2 NO. This discriminates the
    // scope-collapse bug — the +2/+2 must stay on SelfRef only.
    assert!(
        has_kw(&mut runner, bears, &Keyword::Vigilance),
        "CR 613.1f: creatures you control gain Vigilance (Layer 6 scope = Typed Creature/You)"
    );
    assert_eq!(
        effective_pt(&mut runner, bears),
        (2, 2),
        "scope discriminator: +2/+2 is SelfRef-only — must NOT leak onto other creatures you control"
    );

    // (c) Opponent's creature: no Vigilance, unchanged P/T.
    assert!(
        !has_kw(&mut runner, opp, &Keyword::Vigilance),
        "CR 109.5: 'creatures you control' excludes the opponent's creature"
    );
    assert_eq!(
        effective_pt(&mut runner, opp),
        (2, 2),
        "opponent creature P/T unchanged"
    );

    // ----- Scenario B: Lieutenant gate OFF -----
    // Remove the commander from the battlefield so `controls_own_commander`
    // returns false (CR 903.3d). Both split statics share the gate and must
    // deactivate together.
    {
        let state = runner.state_mut();
        state.battlefield.retain(|&id| id != commander);
        state.objects.remove(&commander);
    }

    // (d) No Vigilance from this source on any creature; Angelic Field Marshal
    // back to its base 3/3 (no +2/+2).
    assert!(
        !has_kw(&mut runner, marshal, &Keyword::Vigilance),
        "gate OFF: Angelic Field Marshal loses the Lieutenant-granted Vigilance"
    );
    assert!(
        !has_kw(&mut runner, bears, &Keyword::Vigilance),
        "gate OFF: second P0 creature loses the Lieutenant-granted Vigilance"
    );
    assert_eq!(
        effective_pt(&mut runner, marshal),
        (3, 3),
        "gate OFF: Angelic Field Marshal returns to base 3/3 (no +2/+2)"
    );
}
