import type * as RealModule from "../../src/hooks/useCardImage";

import { useEffect, useState } from "react";

/**
 * Story double for `src/hooks/useCardImage.ts`.
 *
 * The real hook resolves art through the Scryfall lookup maps under
 * `client/public/` — `scryfall-data.json`, `scryfall-printings.json` and
 * friends. Those are generated by the card-data pipeline and gitignored, so a
 * fresh checkout has none of them. Rather than ship a fixture of that schema
 * (which would drift the moment the pipeline changed), this double skips the
 * lookup layer and asks Scryfall for the image by name.
 *
 * It keeps the real hook's contract, so every branch `CardImage` renders stays
 * reachable from an ordinary story with an ordinary card name:
 *
 * - preload in flight → `isLoading`, and the card draws its pulsing skeleton;
 * - preload resolved → `src`, and the card draws its `<img>`;
 * - preload rejected, because the name is not a card or the browser is offline
 *   → `src: null`, and the card draws `CardArtFallback`.
 *
 * Every export is typed against the real module, so a signature change there
 * breaks `pnpm type-check` here instead of drifting silently.
 */

/** Scryfall's `format=image` endpoint, which redirects straight to the CDN. Its
 *  `version` values are the same vocabulary as the hook's `size` option. */
const SCRYFALL_NAMED_IMAGE = "https://api.scryfall.com/cards/named";

export const useCardImage: typeof RealModule.useCardImage = (cardName, options) => {
  const version = options?.size ?? "normal";
  // Scryfall exposes a double-faced card's second half as `face=back`; every
  // face index past the front maps there.
  const face = options?.faceIndex ? "back" : "front";
  const query = `exact=${encodeURIComponent(cardName)}&format=image&version=${version}&face=${face}`;
  const src = cardName ? `${SCRYFALL_NAMED_IMAGE}?${query}` : null;

  const [resolved, setResolved] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(src !== null);

  useEffect(() => {
    if (!src) {
      setResolved(null);
      setIsLoading(false);
      return;
    }

    let isCurrent = true;
    setResolved(null);
    setIsLoading(true);

    const image = new Image();
    // A 404 (no such card) and an offline browser both land on `onerror`, which
    // is precisely when the real hook reports no art.
    image.onload = () => {
      if (isCurrent) {
        setResolved(src);
        setIsLoading(false);
      }
    };
    image.onerror = () => {
      if (isCurrent) {
        setResolved(null);
        setIsLoading(false);
      }
    };
    image.src = src;

    return () => {
      isCurrent = false;
    };
  }, [src]);

  return { src: resolved, isLoading, isRotated: false, isFlip: false };
};

/** Stories render the app's own `CardBackFallback`, so no back art is needed. */
export const useCardBackImage: typeof RealModule.useCardBackImage = () => ({
  src: null,
  isLoading: false,
});

/** Localised art is a preference-store concern the catalog does not exercise. */
export const useLocaleArt: typeof RealModule.useLocaleArt = () => "en";
