pub(crate) mod activation;
pub mod activation_patience;
mod aggro_pressure;
mod anthem_priority;
mod anti_self_harm;
mod blight_value;
mod board_development;
mod board_wipe_telegraph;
mod card_advantage;
mod chalice_avoidance;
mod combat_withdrawal;
pub(crate) mod combo_line;
mod commander_zone_return;
mod condition_gated_activation;
pub(crate) mod context;
mod control_change_awareness;
pub(crate) mod copy_value;
mod cost_reduction;
mod creature_type_choice;
mod crew_timing;
mod cycling_discipline;
mod devotion;
mod discard_payoff;
mod downside_awareness;
mod draw_payoff;
pub(crate) mod effect_classify;
mod effect_timing;
mod equipment_priority;
mod etb_value;
mod evasion_removal_priority;
mod fetch_land_patience;
mod free_outlet_activation;
mod graveyard_types;
pub(crate) mod hand_disruption;
mod hold_mana_up;
mod interaction_reservation;
mod land_animation;
mod land_sequencing;
mod landfall_timing;
mod lethality_awareness;
mod life_total_resource;
mod loop_shortcut;
mod mana_efficiency;
mod mill_targeting;
mod momir_curve;
pub mod mulligan;
mod payment_selection;
mod payoff;
mod pile_partition;
mod planeswalker_loyalty;
mod plus_one_counters;
mod poison;
mod ramp_timing;
mod reactive_self_protection;
mod recursion_awareness;
mod redundancy_avoidance;
pub mod registry;
mod removal_lethality;
mod ritual_sink;
mod sacrifice_cost_mana_gate;
mod sacrifice_land_protection;
mod sacrifice_value;
mod self_bounce_target;
mod self_cost;
mod self_cost_value;
mod self_protection_classify;
mod self_untap_loop;
mod separate_piles_timing;
mod spellskite_priority;
mod spellslinger_casting;
pub(crate) mod stack_awareness;
pub(crate) mod strategy_helpers;
mod sweeper_timing;
mod synergy_casting;
mod tempo_curve;
mod tokens_wide;
mod tribal_lord_priority;
pub(crate) mod tutor;
mod vehicle_deployment;
mod x_cast_gate;
mod x_reference;
mod x_value;

#[cfg(test)]
pub mod tests;

pub use registry::{
    DecisionKind, PolicyId, PolicyReason, PolicyRegistry, PolicyVerdict, TacticalPolicy,
};
